version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NODE_ENV: dev
      TWITCH_OAUTH_TOKEN: oauth:2x2i8s921e4ud7gw8x8zfcj3huxlkc
